Command exited with non-zero status 1
	Command being timed: "bash /root/autodl-tmp/asc_final/icon/ASC26-icon/experiments/ape_from_spinup/scripts/ape_from_spinup.run"
	User time (seconds): 3254706.71
	System time (seconds): 13204.62
	Percent of CPU this job got: 3191%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 28:26:43
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 358844
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 5919
	Minor (reclaiming a frame) page faults: 3549596661
	Voluntary context switches: 512270
	Involuntary context switches: 71937154
	Swaps: 0
	File system inputs: 0
	File system outputs: 3362904
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 1
